// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHFYR_OVrtf-pNG9DreMllgDYxlGi_jc',
    appId: '1:236994710844:web:ff3ecc077d2b7742b1a239',
    messagingSenderId: '236994710844',
    projectId: 'blood-link-113da',
    authDomain: 'blood-link-113da.firebaseapp.com',
    storageBucket: 'blood-link-113da.firebasestorage.app',
    measurementId: 'G-LLVLYQVN8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMFeChdjK3FEuvI_Dxyu4fs2dFEQeZJkg',
    appId: '1:236994710844:android:e43c31193b807fe1b1a239',
    messagingSenderId: '236994710844',
    projectId: 'blood-link-113da',
    storageBucket: 'blood-link-113da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDlpvlew5JefTWL62w5sdJ0wh_71R4RLU',
    appId: '1:236994710844:ios:98f6a6662683fa4eb1a239',
    messagingSenderId: '236994710844',
    projectId: 'blood-link-113da',
    storageBucket: 'blood-link-113da.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDlpvlew5JefTWL62w5sdJ0wh_71R4RLU',
    appId: '1:236994710844:ios:98f6a6662683fa4eb1a239',
    messagingSenderId: '236994710844',
    projectId: 'blood-link-113da',
    storageBucket: 'blood-link-113da.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCHFYR_OVrtf-pNG9DreMllgDYxlGi_jc',
    appId: '1:236994710844:web:9fe7b1a23a94e901b1a239',
    messagingSenderId: '236994710844',
    projectId: 'blood-link-113da',
    authDomain: 'blood-link-113da.firebaseapp.com',
    storageBucket: 'blood-link-113da.firebasestorage.app',
    measurementId: 'G-8J01PDGRGQ',
  );
}
